/**
 * The Synty Prototype Asset Library manifest (SPEC §4.4d, owner directive 2026-08-04).
 *
 * The owner exports Unity Synty prototype packs (complete levels — military maps, biomes — and
 * character packs — military, street racer, city, apocalypse, …) as interactive glTF with Toolkit
 * metadata, hosted at `repo.babylontoolkit.com`, and generates a master `assets.json` describing all
 * of it. The MODEL is made aware of this library so a game build defaults to real prototype models
 * instead of primitives — *"we don't want to hinder the model's creativeness, but we do want the
 * model to be aware of all the Synty prototype models available."*
 *
 * ## Why this is a schema module and not just `JSON.parse`
 *
 * The manifest is generated by an external exporter and promoted by an admin, then INJECTED INTO THE
 * MODEL'S CONTEXT — so bad bytes here are the §4.2.8 silent failure (a garbage block makes every
 * generation worse and throws nothing) and an invented `path` teaches the model asset URLs that 404
 * in the shipped game. Validation therefore refuses before anything is stored (all errors reported at
 * once, the market-price-list rule), and UNKNOWN FIELDS PASS THROUGH UNTOUCHED — the exporter will
 * grow detail (per-object script components, bounds, LODs) that this code predates, and stripping it
 * would make every exporter improvement a two-repo lockstep change.
 *
 * ## The context budget rule (never regress)
 *
 * `buildAssetLibraryIndex` is the ONLY thing that reaches the prompt, and it is HARD-CAPPED: pack
 * summaries plus capped asset-name lists inside an explicit char budget. The full manifest — every
 * asset of every pack with its component detail — must NEVER ride in context wholesale; an
 * "extensive manifest" baked into the prefix is a per-turn bill forever (`spec/context-budget.md`).
 * Awareness is the pack index; detail is what the admin panel and future on-demand levers read.
 */

/**
 * A prefab inside a prop CONTAINER (one file, many props, loaded once as an AssetContainer). The
 * `name` is the exact string `InstantiatePrefabFromContainer` uses — which is why it is validated:
 * a nameless prefab entry is an exporter bug that would otherwise surface as the model instantiating
 * nothing, silently.
 */
export interface AssetLibraryPrefab {
  name: string;
  kind?: string;
  tags?: string[];
  bounds?: unknown;
  components?: unknown;
  [extra: string]: unknown;
}

/** A game-object node that matters: carries script components or marker semantics. */
export interface AssetLibraryNode {
  name: string;
  path?: string;
  purpose?: string;
  components?: unknown;
  children?: AssetLibraryNode[];
  [extra: string]: unknown;
}

/** One placeable asset (a glTF export). Unknown extra fields from the exporter are preserved. */
export interface AssetLibraryAsset {
  /** Relative to the manifest's `baseUrl` — the exact path game code loads. Never absolute. */
  path: string;
  name: string;

  /** level | character | vehicle | prop-container | prop | weapon | building | environment. */
  kind?: string;
  tags?: string[];

  /** How to bring it in: 'scene' (play-contract preload) | 'container' | 'mesh'. */
  load?: string;

  /** The actionable game-object tree: nodes carrying Toolkit script components or markers. */
  nodes?: AssetLibraryNode[];

  /** Prop containers: the instantiable prefabs INSIDE this file, by exact node name. */
  prefabs?: AssetLibraryPrefab[];

  /** Levels: where things start. Without these the model guesses coordinates. */
  spawnPoints?: Array<{ name: string; position: [number, number, number]; [extra: string]: unknown }>;

  /** Complete levels may carry a ready-to-play scene URL (relative, like `path`). */
  sceneUrl?: string;
  [extra: string]: unknown;
}

export interface AssetLibraryPack {
  /** Stable slug, unique across the manifest ("synty-military"). */
  id: string;
  title: string;

  /** Free-form category ("characters", "level", "props", "vehicles", "mixed"). Not an enum on purpose. */
  kind?: string;
  description?: string;
  assets: AssetLibraryAsset[];
  [extra: string]: unknown;
}

export interface AssetLibraryManifest {
  version: number;

  /** Asset `path`s resolve against this. */
  baseUrl: string;
  generated?: string;
  packs: AssetLibraryPack[];
  [extra: string]: unknown;
}

/** Where the master manifest lives — the fetch DEFAULT for the admin panel, never read at generation time. */
export const ASSET_LIBRARY_MASTER_URL = 'https://repo.babylontoolkit.com/assets.json';

export type AssetLibraryValidation = { ok: true; manifest: AssetLibraryManifest } | { ok: false; errors: string[] };

/**
 * Validate candidate bytes into a manifest, reporting EVERY error (an admin fixing an export needs
 * the full list, not a fix-one-refetch-one loop). Refusals, each of which would fail silently later:
 *
 * - a non-object / missing `packs` — nothing to index;
 * - a missing or non-https `baseUrl` — every asset path would resolve against nothing;
 * - duplicate pack ids — the index and any future detail lookup would silently shadow one;
 * - an absolute or traversing asset `path` — the path-traversal wall (`../` or a scheme in a path
 *   escapes `baseUrl`, and the model would ship it verbatim into game code);
 * - an empty pack — an exporter bug worth hearing about at promote time, not at play time.
 */
export function validateAssetLibraryManifest(candidate: unknown): AssetLibraryValidation {
  const errors: string[] = [];

  if (typeof candidate !== 'object' || candidate === null || Array.isArray(candidate)) {
    return { ok: false, errors: ['The manifest must be a JSON object.'] };
  }

  const raw = candidate as Record<string, unknown>;

  if (typeof raw.version !== 'number' || !Number.isFinite(raw.version)) {
    errors.push('`version` must be a number.');
  }

  const baseUrl = typeof raw.baseUrl === 'string' ? raw.baseUrl.trim() : '';

  if (!/^https:\/\/[^\s]+$/.test(baseUrl)) {
    errors.push('`baseUrl` must be an https URL.');
  }

  if (!Array.isArray(raw.packs)) {
    errors.push('`packs` must be an array.');
    return { ok: false, errors };
  }

  const seenPackIds = new Set<string>();

  raw.packs.forEach((pack, packIndex) => {
    const where = `packs[${packIndex}]`;

    if (typeof pack !== 'object' || pack === null) {
      errors.push(`${where} must be an object.`);
      return;
    }

    const p = pack as Record<string, unknown>;
    const id = typeof p.id === 'string' ? p.id.trim() : '';
    const title = typeof p.title === 'string' ? p.title.trim() : '';

    if (!id) {
      errors.push(`${where} is missing a non-empty \`id\`.`);
    } else if (seenPackIds.has(id)) {
      errors.push(`${where} duplicates pack id "${id}".`);
    } else {
      seenPackIds.add(id);
    }

    if (!title) {
      errors.push(`${where} is missing a non-empty \`title\`.`);
    }

    if (!Array.isArray(p.assets) || p.assets.length === 0) {
      errors.push(`${where} ("${id || title || '?'}") must declare at least one asset.`);
      return;
    }

    p.assets.forEach((asset, assetIndex) => {
      const at = `${where}.assets[${assetIndex}]`;

      if (typeof asset !== 'object' || asset === null) {
        errors.push(`${at} must be an object.`);
        return;
      }

      const a = asset as Record<string, unknown>;
      const path = typeof a.path === 'string' ? a.path.trim() : '';

      if (!path) {
        errors.push(`${at} is missing a non-empty \`path\`.`);
      } else if (/^[a-z][a-z0-9+.-]*:/i.test(path) || path.startsWith('/') || path.split('/').includes('..')) {
        errors.push(`${at} path "${path}" must be relative to baseUrl (no scheme, no leading /, no ..).`);
      }

      if (typeof a.name !== 'string' || a.name.trim().length === 0) {
        errors.push(`${at} is missing a non-empty \`name\`.`);
      }

      /*
       * Structured optionals are validated WHEN PRESENT — a sparse manifest is fine, but a present
       * `prefabs` entry without a name would surface as the model instantiating nothing, silently,
       * and a spawn point without a numeric position as a spawn at NaN. Refuse at promote time.
       */
      if (a.prefabs !== undefined) {
        if (!Array.isArray(a.prefabs)) {
          errors.push(`${at} \`prefabs\` must be an array when present.`);
        } else {
          a.prefabs.forEach((prefab, prefabIndex) => {
            const p2 = prefab as Record<string, unknown> | null;

            if (typeof p2?.name !== 'string' || p2.name.trim().length === 0) {
              errors.push(`${at}.prefabs[${prefabIndex}] is missing a non-empty \`name\` (instantiation is BY name).`);
            }
          });
        }
      }

      if (a.nodes !== undefined) {
        if (!Array.isArray(a.nodes)) {
          errors.push(`${at} \`nodes\` must be an array when present.`);
        } else {
          a.nodes.forEach((node, nodeIndex) => {
            const n = node as Record<string, unknown> | null;

            if (typeof n?.name !== 'string' || n.name.trim().length === 0) {
              errors.push(`${at}.nodes[${nodeIndex}] is missing a non-empty \`name\`.`);
            }
          });
        }
      }

      if (a.spawnPoints !== undefined) {
        if (!Array.isArray(a.spawnPoints)) {
          errors.push(`${at} \`spawnPoints\` must be an array when present.`);
        } else {
          a.spawnPoints.forEach((spawn, spawnIndex) => {
            const s = spawn as Record<string, unknown> | null;
            const position = s?.position;

            if (typeof s?.name !== 'string' || s.name.trim().length === 0) {
              errors.push(`${at}.spawnPoints[${spawnIndex}] is missing a non-empty \`name\`.`);
            }

            if (!Array.isArray(position) || position.length !== 3 || position.some((v) => typeof v !== 'number')) {
              errors.push(`${at}.spawnPoints[${spawnIndex}] \`position\` must be [x, y, z] numbers.`);
            }
          });
        }
      }

      const sceneUrl = a.sceneUrl;

      if (
        typeof sceneUrl === 'string' &&
        (/^[a-z][a-z0-9+.-]*:/i.test(sceneUrl) || sceneUrl.startsWith('/') || sceneUrl.split('/').includes('..'))
      ) {
        errors.push(`${at} sceneUrl "${sceneUrl}" must be relative to baseUrl (no scheme, no leading /, no ..).`);
      }
    });
  });

  if (raw.packs.length === 0) {
    errors.push('`packs` is empty — an empty library cannot be promoted (unpin instead).');
  }

  if (errors.length > 0) {
    return { ok: false, errors };
  }

  return { ok: true, manifest: raw as unknown as AssetLibraryManifest };
}

/**
 * The prompt block's hard budget. ~6k chars ≈ 1.5k tokens in the CACHED prefix — real but bounded,
 * and it buys the model the name of every pack and most asset names. Raising it is a measured
 * decision against `spec/context-budget.md`, not a tweak.
 */
export const ASSET_INDEX_CHAR_BUDGET = 6_000;

/** Per-pack cap on listed asset names — past it the index says how many more exist rather than lying. */
const NAMES_PER_PACK = 40;

/** Per-container cap on listed prefab names — the model instantiates BY name, so names must travel. */
const PREFABS_PER_CONTAINER = 24;

/**
 * The compact, DETERMINISTIC index the prompt carries: every pack, its kind/size/description, and a
 * capped list of asset names. Sorted by pack id so byte-identity holds across processes (an unstable
 * prefix busts the cache on every generation — the sorted-skills-index rule).
 *
 * Returns `undefined` when there is nothing to say — the caller must emit NO block at all in that
 * case, never an empty header (telling the model about a library it cannot see is how asset paths
 * get invented).
 */
export function buildAssetLibraryIndex(manifest: AssetLibraryManifest | undefined | null): string | undefined {
  if (!manifest || manifest.packs.length === 0) {
    return undefined;
  }

  const lines: string[] = [
    '# Prototype Asset Library (Synty)',
    '',
    'An asset library of Unity Synty prototype packs exported as interactive glTF with Toolkit metadata —',
    'complete levels and characters/props ready to load. Asset `path`s below resolve against:',
    `${manifest.baseUrl.replace(/\/+$/, '')}/`,
    '',
    '**ALWAYS PREFER THIS LIBRARY for 3D content. Whenever the user has not supplied or named specific',
    'assets, take your 3D models, characters, props and levels from this library (or a pack the user',
    'named) — building geometry out of primitives is the LAST resort, only for what the library truly',
    'lacks, never a default you reach for first.** The index below is already part of your context:',
    'choosing from it costs nothing, is NOT a tool call, and must never delay or displace anything else',
    'you do this turn. Reference assets by their EXACT path below — never invent or guess a library path.',
    '',
  ];

  const packs = [...manifest.packs].sort((a, b) => a.id.localeCompare(b.id));

  for (const pack of packs) {
    const kind = pack.kind ? ` · ${pack.kind}` : '';
    const description = pack.description ? ` — ${pack.description}` : '';
    lines.push(`## ${pack.title} (\`${pack.id}\`${kind}, ${pack.assets.length} assets)${description}`);

    const shown = pack.assets.slice(0, NAMES_PER_PACK);

    const listed = shown
      .map((asset) => {
        const prefabs = Array.isArray(asset.prefabs) ? asset.prefabs : [];

        if (prefabs.length === 0) {
          return `\`${asset.path}\``;
        }

        /*
         * A container's real content is its prefab list — the model loads the file ONCE and
         * instantiates these BY NAME, so the names must travel or the container is opaque.
         */
        const names = prefabs.slice(0, PREFABS_PER_CONTAINER).map((prefab) => prefab.name);
        const more = prefabs.length - names.length;

        return `\`${asset.path}\` (container — instantiate by name: ${names.join(', ')}${more > 0 ? ` …and ${more} more` : ''})`;
      })
      .join(', ');

    const rest = pack.assets.length - shown.length;

    lines.push(rest > 0 ? `${listed} …and ${rest} more in this pack.` : listed);
    lines.push('');
  }

  const full = lines.join('\n');

  if (full.length <= ASSET_INDEX_CHAR_BUDGET) {
    return full;
  }

  /*
   * Over budget: drop every asset-name list and keep every pack HEADER — awareness of what exists
   * survives; the per-asset names are what get summarized. Deterministic (same manifest → same
   * bytes), and the final slice is a last-resort guarantee for a manifest with pathological pack
   * counts, not the normal path.
   */
  const compact: string[] = lines.slice(0, 10);

  for (const pack of packs) {
    const kind = pack.kind ? ` · ${pack.kind}` : '';
    const description = pack.description ? ` — ${pack.description}` : '';
    compact.push(`## ${pack.title} (\`${pack.id}\`${kind}, ${pack.assets.length} assets)${description}`);
    compact.push('');
  }

  compact.push('(Asset-name lists omitted for size — packs are listed with their asset counts.)');

  return compact.join('\n').slice(0, ASSET_INDEX_CHAR_BUDGET);
}

/**
 * The per-request form of the index — the ONE call the proxy makes (§4.4d).
 *
 * `useAssetLibrary` is the user's Control Panel → Features preference, straight off an untrusted
 * request body. Only an explicit `false` opts out: absent/undefined (an older client that never
 * sends the field, a non-browser caller) keeps the shipped default of ON, and any non-boolean junk
 * fails toward the default rather than toward a surprise opt-out. When it IS false, returning
 * undefined makes the caller emit NO block — and since the creation brief's sourcing rule is
 * conditional on the block's presence, the pinned library behaves as if it never existed for this
 * user's project. Pure and exported because the failure mode is silent either way: a leaked block
 * ignores the user's choice, a wrongly-omitted one silently degrades every game they build.
 */
export function assetLibraryIndexForRequest(
  useAssetLibrary: boolean | undefined,
  manifest: AssetLibraryManifest | undefined | null,
): string | undefined {
  return useAssetLibrary === false ? undefined : buildAssetLibraryIndex(manifest);
}
