-- ================================================================================================
-- 0003 — The ledger needs a MONOTONIC ordering key. `created_at` is not one.
--
-- THE BUG (found by `ledger-sql.spec.ts` against a real Postgres; invisible to `FsLedger`):
--
-- Balance is DERIVED from the latest row, and "latest" was defined as:
--
--     order by created_at desc, id desc limit 1
--
-- `created_at` defaults to `now()`, which is the TRANSACTION timestamp — and two ledger rows written
-- in quick succession routinely land on the same one. When they tie, the tiebreak falls to `id`, which
-- is a **random uuid** (`gen_random_uuid()`). So "the latest row" became "a random one of the rows that
-- share a timestamp", and the next append derived its `balance_after` from the WRONG row.
--
-- This is not a theoretical race. The exact sequence that triggers it is the one the agent proxy runs
-- on every failed generation, back-to-back inside one `finally`:
--
--     grant (+10000) → generation debit (-250) → auto-refund (+250)
--
-- The refund would read the GRANT row instead of the DEBIT row and compute a balance that silently
-- skips the debit. The user's balance ends up wrong, nothing throws, and the append-only history looks
-- perfectly plausible. Reproduced: the balance after that sequence came out 9750 instead of 10000.
--
-- THE FIX: an explicit monotonic sequence. `seq` is assigned by the database in commit order, and
-- because every append serializes on the per-user advisory lock inside `append_ledger_entry`, the
-- sequence order for a given user IS the causal order. There is no tie to break.
--
-- Ordering a ledger by wall-clock time was the mistake. Clocks tie, and they go backwards.
-- ================================================================================================

-- The append-only trigger blocks the backfill below, so lift it for the length of this migration.
alter table public.credit_ledger disable trigger forbid_ledger_update;

alter table public.credit_ledger
  add column if not exists seq bigint generated by default as identity;

-- Existing rows (development data only — this predates launch) get a deterministic order.
with ordered as (
  select id, row_number() over (order by created_at, id) as rn
  from public.credit_ledger
  where seq is null
)
update public.credit_ledger l
   set seq = o.rn
  from ordered o
 where l.id = o.id;

alter table public.credit_ledger enable trigger forbid_ledger_update;

alter table public.credit_ledger alter column seq set not null;

-- The read path is "the latest row for this user", so index exactly that.
create unique index if not exists credit_ledger_user_seq_idx on public.credit_ledger(user_id, seq desc);

-- --------------------------------------------------------------------------------------------
-- append_ledger_entry — unchanged except for the ONE line that matters: order by `seq`, not `created_at`.
-- --------------------------------------------------------------------------------------------
create or replace function public.append_ledger_entry(
  p_user_id          uuid,
  p_delta            integer,
  p_reason           text,
  p_generation_id    text default null,
  p_payment_provider text default null,
  p_payment_ref      text default null,
  p_note             text default null,
  p_allow_negative   boolean default false
)
returns public.credit_ledger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_previous integer;
  v_balance  integer;
  v_row      public.credit_ledger;
begin
  -- Serialize concurrent appends for THIS user. Two settlements landing at once queue rather than
  -- both reading the same stale balance.
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  -- `seq desc`, NOT `created_at desc`. Timestamps tie (see the header); a sequence cannot.
  select balance_after into v_previous
  from public.credit_ledger
  where user_id = p_user_id
  order by seq desc
  limit 1;

  v_balance := coalesce(v_previous, 0) + p_delta;

  -- A `generation` debit MAY go negative: we settle AFTER the tokens are spent, and §4.2.1 forbids
  -- killing an in-flight generation for balance. Reality is allowed to overshoot; the gate on the
  -- NEXT generation is what catches it. Nothing else may.
  if v_balance < 0 and not p_allow_negative then
    raise exception 'Insufficient credits: balance would become %', v_balance
      using errcode = 'check_violation';
  end if;

  insert into public.credit_ledger (
    user_id, delta, reason, generation_id, payment_provider, payment_ref, balance_after, note
  ) values (
    p_user_id, p_delta, p_reason, p_generation_id, p_payment_provider, p_payment_ref, v_balance, p_note
  )
  returning * into v_row;

  return v_row;
end;
$$;

revoke all on function public.append_ledger_entry from public, anon, authenticated;
grant execute on function public.append_ledger_entry to service_role;
